name: haornas_2019
description: Hari Olahraga Nasional 2019.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  font_awesome_flutter: any
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/alan.jpg
    - assets/dirc.jpg
    - assets/eko.jpg
    - assets/lilies.jpg
    - assets/raema.jpg
    - assets/rudy.jpg
    - assets/susi.jpg
    - assets/susyana.jpg
    - assets/logo.png
    - assets/taufik.jpg
    - assets/icuk.jpg
